### ISSUE TITLE
Issue with lab AZ-301T02 Module 3

### ISSUE THREAD

**Issue by nlenzDE** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#2]
Hi guys,

I just want to note that the mentioned DSC-configuration example is buggy. The file "lampserver.ps1" cannot be used in that way on a SUSE-box (SUSE uses yast2 or zypper and not yum). Also the package names differ.
Maybe you should prefer to use a Redhat/CentOS template instead...

Regards
Norbert

**Comment by xenadmin** [comment]
This issue was already present in the old course 20535 and already fixed there. Sadly it was ported into this course without the fix. 

https://github.com/MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions/commit/0b16ec447387cd86ef22ddf97679b5ac268d2ae9#diff-99ed0042f833414f4b676f6c0a22bde7
