### ISSUE TITLE
[LabRequest] M1, Lab1- Azure AD

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#38]
Could you please add to lab1 for module 1, , that will cover AAD, AAD B2C, RBAC and/or some other identity topics?
For the moment- lab don't cover significant part of an exam content.

**Comment by djcmct** [comment]
I’d rather see less hands on labs in this course and far more case studies, we’ve already got the 300 course for the button pushing, IMO, this course should be all theory and design

**Comment by SychevIgor** [comment]
Exam include practical part. If preparation will not focus on practice- exam and course will not be aligner

**Comment by djcmct** [comment]
According to the Microsoft website the exam shouldn't include any practical elements

This exam measures your ability to accomplish the following technical tasks: determine workload requirements; design for identity and security; design a data platform solution; design a business continuity strategy; design for deployment, migration, and integration; and design an infrastructure strategy.

Whereas the AZ-300 exam states

This exam measures your ability to accomplish the following technical tasks: deploy and configure infrastructure; implement workloads and security; create and deploy apps; implement authentication and secure data; and develop for the cloud and Azure storage.

Of the 2 descriptions it would suggest that the ability to do practical stuff is measured in the 300 and the ability to plan and design is measured in the 301.

I'd suggest that there should be more labs for AZ-300 and more case studies for AZ-301, otherwise there's no difference between the 2 courses, just my opinion
