### ISSUE TITLE
AZ-301T04_02 - Layout changed?

### ISSUE THREAD

**Issue by Williams-Nest** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#69]
In AZ-301T04 Lab 2 (Building Azure IaaS-Based Server Applications by using Azure Resource Manager Templates and Azure Building Blocks)

Exersize 1, Task 5, Step 4;
"With the Overview selection active, on the storage account blade, click Blobs"

There is no "Blobs" to click on - has the layout changed?

**Comment by polichtm** [comment]
updated

**Comment by MiguelFH** [comment]
In AZ-301T04 Lab 2 (Building Azure IaaS-Based Server Applications by using Azure Resource Manager Templates and Azure Building Blocks)

Exersize 3, Task 3, Step 11;
After run:
azbb -g $RESOURCE_GROUP -s $SUBSCRIPTION_ID -l $LOCATION -p ./reference-architectures/virtual-machines/single-vm/parameters/windows/single-vm.json --deploy

Show the following error:

This command is implicitly deprecated because command group 'group deployment' is deprecated and will be removed in a future release. Use 'deployment group' instead.
{'additionalProperties': {}, 'code': 'InvalidTemplate', 'message': "Deployment template validation failed: 'The template variable 'subnetTemplate' is not valid: The language expression property 'templateLink' doesn't exist, available properties are 'template, templateHash, parameters, mode, provisioningState'.. Please see https://aka.ms/arm-template-expressions for usage details.'.", 'target': None, 'details': None, 'additionalInfo': [{'additionalProperties': {}, 'type': 'TemplateViolation', 'info': {'lineNumber': 21, 'linePosition': 159, 'path': 'properties.template.variables.subnetTemplate'}}]}

  error: error executing az
  status: 1
  arguments: group deployment create --name bb-02-nsg --subscription 0c1c48fc-9f31-46d6-a942-72b0494bd5b9 --resource-group AADesignLab0303-RG --template-uri https://raw.githubusercontent.com/mspnp/template-building-blocks/v2.2.0/templates/buildingBlocks/networkSecurityGroups/networkSecurityGroups.json --parameters @/home/alberto/single-vm-output-02.json
